version: '2'
services:
#  kafka:
#    container_name: kafka
#    image: spotify/kafka
#    ports:
#      - "2181:2181"
#      - "9092:9092"
  human-inspectionreport:
    build: human-inspectionreport/
    container_name: human-inspectionreport
#    depends_on:
#      - kafka
    ports:
      - "8091:8080"
#    links:
#      - kafka:kafka_host
#    environment:
#      - ZOOKEEPER_CONNECT=kafka_host:2181
#      - KAFKA_BOOTSTRAP_SERVERS=kafka_host:9092
  human-maintenancereport:
    build: human-maintenancereport/
    container_name: human-maintenancereport
#    depends_on:
#      - kafka
    ports:
      - "8092:8080"
#    links:
#      - kafka:kafka_host
#    environment:
#      - ZOOKEEPER_CONNECT=kafka_host:2181
#      - KAFKA_BOOTSTRAP_SERVERS=kafka_host:9092
  human-materialcertificate:
    build: human-materialcertificate/
    container_name: human-materialcertificate
    ports:
      - "8093:8080"
  human-materialchange:
    build: human-materialchange/
    container_name: human-materialchange
    ports:
      - "8094:8080"
  human-productionplan:
    build: human-productionplan/
    container_name: human-productionplan
    ports:
      - "8095:8080"
